import Head from "next/head";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Results from "../components/Results";
import requests from "../utils/requests";
import Image from "next/image";
import tmdb from "../public/tmdb.svg";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>TMDB Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <Results results={results} />
      <div className="flex justify-center">
        <Image
          className="object-contain"
          src={tmdb}
          alt="Logo"
          width={100}
          height={100}
        />
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const req = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    } `
  ).then((res) => res.json());

  return {
    props: {
      results: req.results,
    },
  };
}
